apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversao-temperatura
  labels:
    app: conversao-temperatura
    run: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conversao-temperatura
      run: webapp
  template:
    metadata:
      labels:
        app: conversao-temperatura
        run: webapp
    spec:
      containers:
        - name: conversao-temperatura
          image: eaojunior/conversao-temperatura:latest
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 8080