apiVersion: v1
kind: Service
metadata:
  labels:
    app: conversao-temperatura
  name: conversao-temperatura
spec:
  selector:
    app: conversao-temperatura
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30000